### ISSUE TITLE
Do not deploy new version because of doc changes

### ISSUE THREAD

**Issue by lipkau** [AtlassianPS/JiraPS#122]
### Expected Behavior
Changes to the documentations (&co) do not trigger a new release to the PSGallery.
* .vscode/
* assets/
* build/
* docs/
* tools/
* .git*
* appveyor.yml
* CHANGELOG.md
* LICENSE
* README.md

### Current Behavior
Every PUSH will trigger a new version in the PSGallery, even if files that are not published are changed

### Possible Solution
* [Skip CI if HEAD only contains exception files](https://www.appveyor.com/docs/how-to/filtering-commits/#commit-files-github-and-bitbucket-only)
  - this will not only not deploy, but skip CI completely.
  - if this method should be chose, only files that are deployed to the gallery and test files should be watched for
  - all changes to files like `CHANGELOG.md` and similar shall only be pushed in a PR (as suggested in `git flow`)
* .

**Comment by lipkau** [comment]
@replicaJunction do you have an opinion on that?

**Comment by replicaJunction** [comment]
Sure, this seems appropriate - there's no reason to update the gallery if nothing published should change. I don't think this should affect ReadTheDocs, since I don't think it and AppVeyor know about each other, but it's something to keep an eye on, just in case.

We probably do want to trigger CI if commits were made to `tests`, though - for example, if a new feature is committed that breaks a test, the next commit might only be to the test in question.

**Comment by lipkau** [comment]
I believe this is now implemented. I need to do some more testing
