### ISSUE TITLE
Feature Attachments

### ISSUE THREAD

**Issue by lipkau** [AtlassianPS/JiraPS#137]
# [api/2/attachment](https://docs.atlassian.com/jira/REST/cloud/#api/2/attachment)
## Add Attahment
* [ ] `Add-JiraAttachment`
Upload a local file to the server and attach it to an Issue
[POST /rest/api/2/issue/{issueIdOrKey}/attachments](https://docs.atlassian.com/jira/REST/cloud/#api/2/issue/{issueIdOrKey}/attachments-addAttachment)
### Parameter
  + `-Issue` _int / PSJira.Issue_ **mandatory**
  + `-FilePath` _string / FileInfo_ **mandatory**
### Helpful links
  + The docu only has an example for curl. Which uses the flag `-F`. Documented [here](https://curl.haxx.se/docs/manpage.html#-F)
  + [How to send binaries in `multipart/form-data` using powershell](https://stackoverflow.com/questions/22491129/how-to-send-multipart-form-data-with-powershell-invoke-restmethod)
### Output
> PSJira.Attachment

## Get an Attachment from an Issue
* [ ] PSJira.Issue should have the property `Attachment` of type `PSJira.Attachment`

## Remove an Attachment
+ [ ] `Remove-JiraAttachment`
Remove an Attachment from the server
[DELETE /rest/api/2/attachment/{id}](https://docs.atlassian.com/jira/REST/cloud/#api/2/attachment-removeAttachment)
### Parameter
  + `-Id` _integer / PSJira.Attachement_ **mandatory** - ValueFromPipeline, ValueFromPipelineByPropertyName
### Output
> Boolean

**Comment by beaudryj** [comment]
thanks for making that quick :)

**Comment by lipkau** [comment]
**please note**: any contribution is welcome. Not all listed APIs/functions must be implemented at the same time.
This issue will track the development of the features

**Comment by tehfonz** [comment]
```
function Upload-JiraCSV($jiraTicket, $filepath)`
{
    $wc = new-object System.Net.WebClient
    $wc.Headers.Add("Authorization", $basicAuthValue)
    $wc.Headers.Add("X-Atlassian-Token", "no-check")
    $wc.Headers.Add("Content-Type","multipart")
    $wc.UploadFile("http://<URL>/rest/api/2/issue/$jiraTicket/attachments", $(Resolve-Path $filepath))
}
Upload-JiraCSV <ISSUE-KEY> <direct file path> | Out-Null
```

```
$user = '<username>'
$pass = '<password>'
$pair = "$($user):$($pass)"
$encodedCreds = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($pair))
$basicAuthValue = "Basic $encodedCreds"
```

**Comment by swatkris** [comment]
@lipkau,
Hello Oliver,
could you please post a sample how to use of "Add-JiraAttachment".
Sorry.
Thank you
SWATKRIS

**Comment by lipkau** [comment]
```powershell
Add-JiraAttachment -Issue 'FOO-1234' -FilePath 'C:\file.txt'
```

**Comment by swatkris** [comment]
@lipkau,
Thank you very much, but for Add-JiraIssueComment there is also a file with .ps1. But for Add-JiraAttachment... I can´t find anyone... is it right ? Where should it be ? 
Thanks agein
Yours
swatkris

**Comment by lipkau** [comment]
No.
This ticket is requesting the function to be written

**Comment by dhegland** [comment]
:) Thanks Oliver, looking forward to having this feature, need help developing it?  :)

**Comment by lipkau** [comment]
Yes. That's what the `up-for-grabs` label is for :-D

**Comment by aaronsb** [comment]
I would suggest taking a look at this super helpful post on multi part uploads: 

http://blog.majcica.com/2016/01/13/powershell-tips-and-tricks-multipartform-data-requests/

Author wrote a Invoke-MultipartFormDataUpload function which appears to fulfill the rest api's requirement for rfc 1867 content format.

I think this would fit best as an appendex to Invoke-JiraMethod, since that itself is a wrapper for Invoke-WebRequest.

The Invoke-MultipartFormDataUpload would appear to suppliment the base function of iwr, so it would make sense that the jira specific wrapper for iwr would have this capability to enhance iwr (within the wrapper)

From there, several different type of "helpers" to feed invoke-webrequest with the multipart method could be written for file uploads and avatars for jira. Confluence/PS would benefit from this same enhancement.

**Comment by lipkau** [comment]
@beaudryj already has some working code.
waiting on him to submit a PR :-)
