### ISSUE TITLE
Allow Custom Server URL

### ISSUE THREAD

**Issue by scoro-bbc** [AtlassianPS/JiraPS#497]
## Context
It would be helpful to allow Set-JiraConfigServer to allow for customised Server URLs

> **Is your feature request related to a problem? Please describe.**

## Description
Currently `Set-JiraConfigServer  -Server`  allows you to set the root path to the JIRA Server.  However JIRA Server does allow you to customise the URL for JIRA API which can have different elements to the defaults used when requesting issues

For instance if a server has been set up to have `/rest/agile` as the initial elements in the path rather than `rest/api/2` when call is made to the Server the path becomes badly formed.

For example 
https://jira.dev.bob.com/rest/agile, becomes  https://jira.dev.bob.com/rest/agile/rest/api/2/

> **Describe the solution you'd like**
It would be helpful to either have a Set-CustomConfigServer -Server that allows the user to set the custom base path, with ConfigServer check in PS Functions to check if using a CustomConfigServer object and then to make use of the custom URL

**Comment by lipkau** [comment]
Hello @scoro-bbc .

The Agile Board (Scrum and Kanban) used to be a plugin in Jira but have been integrated into the default Jira bundle.
But the API was not integrated - that's why you see a fundamental difference in the base URL of the API.

I have started a Module which extends `JiraPS` (requires it to be set up): https://github.com/AtlassianPS/JiraAgilePS
But the module was never finished. So if it's lacking a functionality that you need, consider contributing with a PR :-)
